name: AI Dev Agent Loop
on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 6 * * 1-5"

jobs:
  loop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Configure git identity
        run: |
          git config --global user.name "AI Dev Agent"
          git config --global user.email "agent@basstian-ai.com"

      - name: Run ai-dev-agent (full loop)
        uses: basstian-ai/ai-dev-agent@v1.0.3   # <-- pin to your new tag
        with:
          config: ${{ vars.AGENT_CONFIG_PATH || '.ai/agent.yml' }}
          max-diff-lines: ${{ vars.AGENT_MAX_DIFF_LINES || '400' }}
          repair-only: ${{ vars.AGENT_REPAIR_ONLY || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_TEAM_ID: ${{ vars.VERCEL_TEAM_ID }}
