name: Checks
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder lint
        run: echo "TODO: add linter" && true
      - name: Placeholder tests
        run: echo "TODO: add tests" && true
