---
name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".ai/*.yml .ai/**/*.yml .github/workflows/*.yml"
          format: parsable
          strict: false
          no_warnings: false

      - name: TODO linter placeholder
        run: echo "TODO: add linter"

      - name: TODO tests placeholder
        run: echo "TODO: add tests"
